name: food
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  # # broka app
  # mqtt_client: ^10.3.0
  # syncfusion_flutter_charts: ^28.1.41
  # iconsax: ^0.0.8
  # # tiktok
  # video_player: ^2.9.2
  # # family_clinic
  # flutter_rating_bar: ^4.0.1
  # # chat app
  # cloud_firestore: ^5.4.0
  # provider: ^6.1.2
  # firebase_core: ^3.4.0
  # firebase_auth: ^5.2.0
  # # broka
  # firebase_storage: ^12.2.0
  # image_picker: ^1.1.2
  # connectivity_plus: ^6.1.3
  # file_picker: ^8.0.5
  # hive: ^2.2.3
  # cached_network_image: ^3.4.0
  # shared_preferences: ^2.2.3
  # # flemo app
  # blurry_modal_progress_hud: ^1.1.1
  # flutter_map: ^7.0.2
  # latlong2: ^0.9.1
  # # flemo app test 
  # flutter_stable_geo_fence: ^1.0.0
  # fluttertoast: ^8.2.8
  # poly_geofence_service: ^4.0.0+1
  # nouva neons
  font_awesome_flutter: ^10.8.0
  flutter_3d_controller: ^2.0.3
  model_viewer_plus: ^1.7.2
  intl: ^0.20.2
  iconsax: ^0.0.8
  http: ^1.3.0
  dotenv: ^4.2.0
  # flutter_dotenv: ^5.2.1
  path_provider: ^2.1.5
  file_picker: ^10.1.2
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  connectivity_plus: ^6.1.4
  smooth_page_indicator: ^1.2.1
  envied: ^1.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


  # ---- ADD THESE LINES ----
  hive_generator: ^2.0.1 # Use the latest compatible version
  build_runner: ^2.4.11  # Use the latest compatible version
  # -----------------------
  

  shared_preferences: ^2.2.3 # For saving theme preference
  permission_handler: ^11.3.1 # For requesting storage permissions (best practice)
  package_info_plus: ^8.0.0  # To get app package name for export path
  

  envied_generator: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    # - .env
    - assets/user.jpg
    - assets/ai_profile.jpg
    - assets/lib_broka/images/
    - assets/lib_broka/images/category/
    - assets/lib_broka/images/carousel/
    - assets/lib_broka/images/just_for_you/
    - assets/map_placeholder.png


    # - assets/user.jpg
    # - assets/user_2.jpg
    # - assets/grey.png
    # - assets/video.mp4
    

    
    # # FAMILY
    # - assets/famil_y_health_clinic/services/
    # - assets/famil_y_health_clinic/popular/

    # # nouva neon
    # - assets/nouva_neon/images/
    # - assets/nouva_neon/3dmodels/
    # - assets/nouva_neon/images/music_genres/


    